name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: make clean
        run: make clean
      - name: make compile
        run: make compile
