name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/QSPMinimalRendering
      run: cmake .

    - name: Build Raycaster
      working-directory: ${{runner.workspace}}/QSPMinimalRendering
      shell: bash
      run: make W3D

    - name: Build Tests
      working-directory: ${{runner.workspace}}/QSPMinimalRendering
      shell: bash
      run: make build_tests

    - name: Run Tests
      working-directory: ${{runner.workspace}}/QSPMinimalRendering
      shell: bash
      run: make run_tests_wo
